//
// Created by belisariops on 9/25/17.
//

#ifndef CONVOLUTIONALNETWORK_CONVOLUTIONALNEURALNETWORK_H
#define CONVOLUTIONALNETWORK_CONVOLUTIONALNEURALNETWORK_H


class ConvolutionalNeuralNetwork {

};


#endif //CONVOLUTIONALNETWORK_CONVOLUTIONALNEURALNETWORK_H
